/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mcs.convention.plugin;

import org.gradle.api.plugins.JavaPluginConvention;
import org.gradle.testfixtures.ProjectBuilder;
import org.gradle.api.Project;
import org.junit.Test;
import static org.junit.Assert.*;

/**
 * A simple unit test for the 'mcs.convention.plugin.greeting' plugin.
 */
//public class McsConventionPluginTest {
//    @Test public void pluginRegistersATask() {
//        // Create a test project and apply the plugin
//        Project project = ProjectBuilder.builder().build();
//        project.getPlugins().apply("mcs.convention.plugin.standard");
//
//        // Verify the result
//        //assertNotNull(project.getTasks().findByName("greeting"));
//        assertNotNull(project.getConvention().getPlugin(JavaPluginConvention.class).getTargetCompatibility());
//        assertNotNull(project.getConvention().getPlugin(JavaPluginConvention.class).getSourceCompatibility());
//    }
//}
